name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Save PEM key from secret
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem

    - name: Copy jar to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.jar ec2-user@${{ secrets.EC2_HOST }}:~/springboot-app/app.jar

    - name: Restart Spring Boot on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/springboot-app/app.jar > app.log 2>&1 &
        EOF

